before-install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
env:
env:
  global:
    - secure: OVCBOhg2IilVc3qjj+DdCrewXxH4LqB7pyQAtVOP2nVegV2ZYVD9AZjjSp2gcd3GgTDWyFNbjta9qwn1i3aVFt+TfH2U5NMjleZTlWPgBCN9XJPQI3SNiMzYDI+qcEWcbNSRkSKFx5xFI9s3QaB9wWOMy0/uNSMo8OokMWMUZjICGMXyN0xYGbUskGDff4BBge13Qjboc2c24wTU5WvlGT8mSy0g10AofbYDI5LkDnVmbqSv0KcxzVlUovFnqtOFphzOZiLLm4X64WJKcHVsQbImNpfSGNFnTpBDKmom0CVs19sl+bznPtR/6/n0vQDmm6Wfu9d5JuOYGOMapUpWmwRXMRA9MSSDjhSGtrm01G+/crRdFO+00vSBAxZjocpWldX5hrQGNbjhw+CU+BKw57T3vZ+5lpb4DlAmU9TbplZ10k54D06Z8lOtQN11ZAXkrhccVIdGfYzDwcg21xvkR+SVoq8+np/9ex4ps5gBpsDWAQ5pHBDp6sEX9JSzRZQFR3xuSB/zkwcTe2mozaqzr9rRc5A83M/OOKmHoPyuNI8TnzMQQP2Hl35W15ab5anbhpUmpEhlea8gQsC8ktEgYPfL+x75XwhY/ooPUtSqIH7wZYJms7niXeLicamws4GpM65w02G6z5kMEAH1wJkEY458PvVlWsIeKDO1Hn1YC7k=
    - secure: Nf6BEvDEr5O4l0J+G00TfPKuTCn15d+d9YKR8DkqMkKpnZkZO0M+PsbeXe6fZcxuXcTFvOYxFSv/YaEVNe+IUiHHpExdrk7lxpuKN4gI0oSWXojtKKkt1GZ85vZDL3vnAHYKT07uEZNHsONziNuR3Dy7GeGjN/irb9OgmXoiXmVciKZiuNP1q5Msr409V6BWMvFx2qL5M7eDzjHW/Oh7LiFsNFPcrUhzHe8SqUhOTlfkfz3YpZvh80NCwnfiZNP0yVBRIpHZDFnzgTZimNwuS3ya479FBR6Oyt8gKOe7VoiLfef+/kyAMy8moXO9722bi4nay4ic7MJ0uRBeETgEtgdby/nk/5toJvO3nmX0JSGc24rJqLZbAjoXjJlg2gAaCscsNaQGFh5VJ4Ih4CTTc1s9/D4LpgkcX4/rahq5WK89XHY6ps1LCqskC/5NUoNy1844gFmk3SzZq6/oOpVQAA/R50wGj03SqGZqaoEtjf2xhBtiSsw7zRhMMs/FR/HWhGjVgquUX+y74B437T0csddBX/BIsA1ThjV3ENiJPSJwQnbDuZUBE7WhnRv7S6lIP0F/duW3DqxMpuojZdSCiazIaTSljggh7aavib1EcZy4z1Gpslcgov9eKlVnX4/BVos2wwbRvj5Zt3+ku8fSienoqu/8a5QudbhJm5SbySM=
addons:
  sauce_connect: true
language: node_js
node_js:
- 0.12
script: |
  ./node_modules/.bin/shortcake test-ci
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: Q9D47UyFU0p2A9/ZMUhFD26kAl7vPn7wkW2XsnZdC1Z/65SapF8Myn1WtG28lFwYkDLc+i75atMrzFgsQBkFXV38grDNb8FSDArtkMSLVqRutNXlDzYh4F3kAdThO2rHrji68OdLj89j5FbR8iAEjE0sahI1t+GY0hQ/pKHxpOf2qVdECPYX9t4r88oDBEn6FV3IyIm9On+XqD4MSMm0ek2UbFjYx59g4DGKBwc+M2czDTvJCrDNCCahXVHIwSZ1qvifIaGIQNK6Gtm57vVLufAmCOniRFFj3Wy6AsoxBx6Ogm1k4t6FlgJyvav5NhnH7GESCAGx8awODBHGWIIvI9uOd9SbWOjhKm0LdimeJ4oRuKhbQ/2XoLG9ZOLpdnYfUaBii98fBfiuoDyavgUHLP2U1qHde0+Hqid8djR8kppw/jWkZSSmI9eLm8PfYCVS8ZDXEtS3v14VXQi2w/XFJFr9PAde1gGmrUURe4/ei3vGfF8wCk+PRylE4+f3m2QpYdKJM1tdowh+YFXx8G26XFCCGVWlNGMfPaBv3Pn905SJSxBqgSep/01Go4j43o7wJADQG+hejn8Y30NjBuwDvpooFz2HJfXG7XF4r8ghcD11iPhZTUyUN5veTJGevgRvr9sMZDkX/vaTFqqXKnKQuwcqvA01NNVjQXUat6SEZQY=
